# AgentArts Dockerfile
# Generated by AgentArts CLI

FROM python:3.12-slim

# Set container environment marker
ENV DOCKER_CONTAINER=true
ENV HUAWEICLOUD_SDK_REGION=cn-southwest-2

# Create non-root user for security
RUN groupadd -g 1000 appuser && \
    useradd -u 1000 -g 1000 -m -s /bin/bash appuser

WORKDIR /app

RUN chown appuser:appuser /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

RUN chown -R appuser:appuser /app

EXPOSE 8080

USER appuser

CMD ["python", "-m", "demo.app"]
